#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG STATIC CARD HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

#include <initializer_list>
#include <string>
#include <vector>

inline std::string filter_declared_options(const std::string &options,
                                           std::initializer_list<const char *> declared) {
  std::vector<std::string> parts;
  std::string current;
  for (char ch : options) {
    if (ch == ',') { parts.push_back(current); current.clear(); }
    else current += ch;
  }
  parts.push_back(current);
  std::string out;
  for (const char *name : declared) {
    const std::string key(name);
    for (const std::string &raw : parts) {
      std::size_t begin = raw.find_first_not_of(" \t");
      if (begin == std::string::npos) continue;
      std::size_t end = raw.find_last_not_of(" \t");
      const std::string text = raw.substr(begin, end - begin + 1);
      const std::size_t eq = text.find('=');
      if ((eq == std::string::npos ? text : text.substr(0, eq)) != key) continue;
      if (!out.empty()) out += ",";
      out += text;
      break;
    }
  }
  return out;
}

template<typename Config>
inline bool normalize_saved_config_static(Config &config) {
  if (config.type == "agenda") {
    config.icon = "Auto";
    config.icon_on = "Auto";
    config.sensor.clear();
    config.unit.clear();
    config.type = "agenda";
    config.precision.clear();
    config.options = filter_declared_options(config.options, {"agenda_days", "agenda_hide_empty"});
    return true;
  }
  if (config.type == "internal") {
    config.type = "internal";
    config.options.clear();
    return true;
  }
  if (config.type == "light_brightness") {
    config.sensor.clear();
    config.type = "light_brightness";
    config.options.clear();
    return true;
  }
  if (config.type == "light_switch") {
    config.sensor.clear();
    config.unit.clear();
    config.type = "light_switch";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  if (config.type == "light_temperature") {
    config.type = "light_temperature";
    config.options.clear();
    return true;
  }
  if (config.type == "push") {
    config.type = "push";
    config.options.clear();
    return true;
  }
  if (config.type == "screen_lock") {
    config.entity.clear();
    config.label.clear();
    config.icon = "Lock";
    config.icon_on = "Lock Open";
    config.sensor.clear();
    config.unit.clear();
    config.type = "screen_lock";
    config.precision.clear();
    config.options.clear();
    return true;
  }
  if (config.type == "slider") {
    config.sensor.clear();
    config.type = "slider";
    config.options.clear();
    return true;
  }
  return false;
}
