#pragma once

#include <string>

// GENERATED COMPANION CAPABILITIES - do not edit by hand
// Generated by scripts/build.py from product/v2/companion_capabilities.json.

constexpr int COMPANION_CAPABILITY_VERSION = 1;

struct CompanionWindowCapability { const char *id; const char *label; };
inline constexpr CompanionWindowCapability COMPANION_WINDOW_CAPABILITIES[] = {
  {"window.close", "Close"},
  {"window.minimize", "Minimise"},
  {"window.hide", "Hide App"},
  {"window.fullscreen", "Full Screen"},
  {"window.fill", "Fill Desktop"},
  {"window.center", "Centre"},
  {"window.left", "Left"},
  {"window.right", "Right"},
  {"window.top", "Top"},
  {"window.bottom", "Bottom"},
  {"window.restore", "Return to Previous Size"},
  {"window.arrange.left-right", "Left & Right"},
  {"window.arrange.right-left", "Right & Left"},
  {"window.arrange.top-bottom", "Top & Bottom"},
  {"window.arrange.bottom-top", "Bottom & Top"},
  {"window.arrange.left-quarters", "Left & Quarters"},
  {"window.arrange.right-quarters", "Right & Quarters"},
  {"window.arrange.top-quarters", "Top & Quarters"},
  {"window.arrange.bottom-quarters", "Bottom & Quarters"},
};

struct CompanionMetricCapability { const char *id; const char *label; const char *label_key; const char *unit; };
inline constexpr CompanionMetricCapability COMPANION_METRIC_CAPABILITIES[] = {
  {"stat.cpu", "Processor", "processor", "%"},
  {"stat.memory", "Memory", "memory", "%"},
  {"stat.memory_free", "Memory", "memory", "%"},
  {"stat.storage", "Storage", "storage", "%"},
  {"stat.storage_free", "Storage", "storage", "%"},
  {"stat.battery", "Battery", "battery", "%"},
  {"stat.network_throughput", "Network", "network_throughput", "MB/s"},
};

inline constexpr const char *COMPANION_MEDIA_ACTION_IDS[] = {
  "media.play_pause",
  "media.previous",
  "media.next",
};

constexpr const char *COMPANION_MEDIA_PLAY_PAUSE_ACTION = "media.play_pause";

inline const CompanionWindowCapability *companion_window_capability(const std::string &id) {
  for (const auto &item : COMPANION_WINDOW_CAPABILITIES) if (id == item.id) return &item;
  return nullptr;
}

inline const CompanionMetricCapability *companion_metric_capability(const std::string &id) {
  for (const auto &item : COMPANION_METRIC_CAPABILITIES) if (id == item.id) return &item;
  return nullptr;
}

inline bool companion_generated_media_action_valid(const std::string &id) {
  for (const auto *item : COMPANION_MEDIA_ACTION_IDS) if (id == item) return true;
  return false;
}
