// =============================================================================
// GENERATED ENTITY BACKUP MAP - do not edit by hand
// Generated by scripts/build.py from common/config/entity_names.json.
// =============================================================================
// Maps espcontrol.backup v2 envelope fields onto ESPHome entities. Entities are
// identified by NAME, not object_id: web_server matches names first and logs
// object_id URLs as deprecated (removal in 2026.7.0).
//
// `derived` marks a field whose value is not a plain 1:1 entity read/write - it
// has a hand-written rule in config_api.h. The build.py validator requires the
// two to stay in step.
// =============================================================================
#ifndef ESPCONTROL_ENTITY_BACKUP_MAP_GENERATED_H
#define ESPCONTROL_ENTITY_BACKUP_MAP_GENERATED_H

#include <cstddef>

struct EntityBackupField {
  const char *key;           // entity_names.json key
  const char *entity_name;   // exact ESPHome entity name
  const char *domain;        // text | select | number | switch
  const char *section;       // root | settings | screen
  const char *field;         // envelope field name
  bool derived;              // needs a hand-written rule, not a plain write
};

inline constexpr EntityBackupField ENTITY_BACKUP_FIELDS[] = {
    {"button_order", "Button Order", "text", "root", "button_order", false},
    {"button_on_color", "Button On Color", "text", "root", "button_on_color", false},
    {"indoor_temp_enable", "Indoor Temp Enable", "switch", "settings", "indoor_temp_enable", false},
    {"outdoor_temp_enable", "Outdoor Temp Enable", "switch", "settings", "outdoor_temp_enable", false},
    {"screen_clock_bar", "Screen: Clock Bar", "switch", "settings", "clock_bar", false},
    {"screen_clock_bar_time", "Screen: Clock Bar Time", "switch", "settings", "clock_bar_time", false},
    {"clock_bar_temperature_entities", "Clock Bar: Temperature Entities", "text", "settings", "clock_bar_temperature_entities", false},
    {"screen_network_status_icon", "Screen: Network Status Icon", "switch", "settings", "network_status_icon", false},
    {"voice_services", "Voice Services", "switch", "settings", "voice_services", false},
    {"alarm_delay_audio", "Alarm Delay: Audio", "switch", "settings", "alarm_delay_audio", false},
    {"alarm_delay_tts", "Alarm Delay: TTS", "switch", "settings", "alarm_delay_tts", false},
    {"alarm_delay_entry_announcement", "Alarm Delay: Entry Announcement", "text", "settings", "alarm_delay_entry_announcement", false},
    {"alarm_delay_exit_announcement", "Alarm Delay: Exit Announcement", "text", "settings", "alarm_delay_exit_announcement", false},
    {"alarm_delay_beep_volume", "Alarm Delay: Beep Volume", "number", "settings", "alarm_delay_beep_volume", false},
    {"alarm_delay_final_countdown", "Alarm Delay: Final Countdown", "number", "settings", "alarm_delay_final_countdown", false},
    {"screen_temperature_degree_symbol", "Screen: Temperature Degree Symbol", "switch", "settings", "temperature_degree_symbol", false},
    {"screen_subpage_chevron", "Screen: Subpage Chevron", "switch", "settings", "subpage_chevron", false},
    {"screen_temperature_unit", "Screen: Temperature Unit", "select", "settings", "temperature_unit", false},
    {"indoor_temp_entity", "Indoor Temp Entity", "text", "settings", "indoor_temp_entity", false},
    {"outdoor_temp_entity", "Outdoor Temp Entity", "text", "settings", "outdoor_temp_entity", false},
    {"screensaver_mode", "Screensaver Mode", "text", "settings", "screensaver_mode", true},
    {"screen_saver_action", "Screen Saver: Action", "select", "settings", "screensaver_action", true},
    {"presence_sensor_entity", "Presence Sensor Entity", "text", "settings", "presence_sensor_entity", false},
    {"screen_saver_media_player_sleep_prevention", "Screen Saver: Media Player Sleep Prevention", "switch", "settings", "media_player_sleep_prevention", false},
    {"media_player_sleep_prevention_entity", "Media Player Sleep Prevention Entity", "text", "settings", "media_player_sleep_prevention_entity", false},
    {"screen_saver_cover_art", "Screen Saver: Cover Art", "switch", "settings", "cover_art_screensaver", false},
    {"screen_saver_cover_art_entity", "Screen Saver: Cover Art Entity", "text", "settings", "cover_art_media_player_entity", false},
    {"screen_saver_cover_art_secondary_entity", "Screen Saver: External Source Media Entity", "text", "settings", "cover_art_secondary_media_player_entity", false},
    {"screen_saver_cover_art_conditions", "Screen Saver: Cover Art Conditions", "text", "settings", "cover_art_attribute_conditions", false},
    {"screen_saver_cover_art_delay", "Screen Saver: Cover Art Delay", "number", "settings", "cover_art_delay", false},
    {"screen_saver_track_overlay_duration", "Screen Saver: Show Track Overlay", "number", "settings", "cover_art_track_overlay_duration", false},
    {"screen_saver_hide_cover_art_external_input", "Screen Saver: Hide for external sources", "switch", "settings", "cover_art_hide_external_input", false},
    {"home_assistant_artwork_protocol", "Home Assistant Artwork Protocol", "select", "settings", "home_assistant_artwork_protocol", false},
    {"home_assistant_artwork_port", "Home Assistant Artwork Port", "number", "settings", "home_assistant_artwork_port", false},
    {"screen_saver_daytime_clock_brightness", "Screen Saver: Daytime Clock Brightness", "number", "settings", "clock_brightness_day", false},
    {"screen_saver_nighttime_clock_brightness", "Screen Saver: Nighttime Clock Brightness", "number", "settings", "clock_brightness_night", false},
    {"screen_saver_dimmed_brightness", "Screen Saver: Dimmed Brightness", "number", "settings", "screensaver_dimmed_brightness", false},
    {"screensaver_timeout", "Screensaver Timeout", "number", "settings", "screensaver_timeout", false},
    {"home_screen_timeout", "Home Screen Timeout", "number", "settings", "home_screen_timeout", false},
    {"screen_saver_clock", "Screen Saver: Clock", "switch", "settings", "clock_screensaver", true},
    {"screen_timezone", "Screen: Timezone", "select", "settings", "timezone", false},
    {"screen_language", "Screen: Language", "select", "settings", "language", false},
    {"screen_clock_format", "Screen: Clock Format", "select", "settings", "clock_format", false},
    {"screen_ntp_server_1", "Screen: NTP Server 1", "text", "settings", "ntp_server_1", false},
    {"screen_ntp_server_2", "Screen: NTP Server 2", "text", "settings", "ntp_server_2", false},
    {"screen_ntp_server_3", "Screen: NTP Server 3", "text", "settings", "ntp_server_3", false},
    {"screen_automatic_brightness", "Screen: Automatic Brightness", "switch", "screen", "automatic_brightness", false},
    {"screen_schedule_enabled", "Screen: Schedule Enabled", "switch", "screen", "schedule_enabled", true},
    {"screen_schedule_trigger", "Screen: Schedule Trigger", "text", "screen", "schedule_trigger", false},
    {"screen_schedule_sensor_activation", "Screen: Schedule Sensor Activation", "select", "screen", "schedule_sensor_activation", false},
    {"screen_schedule_mode", "Screen: Schedule Mode", "select", "screen", "schedule_mode", true},
    {"screen_schedule_on_hour", "Screen: Schedule On Hour", "number", "screen", "schedule_on_hour", false},
    {"screen_schedule_off_hour", "Screen: Schedule Off Hour", "number", "screen", "schedule_off_hour", false},
    {"screen_schedule_wake_timeout", "Screen: Schedule Wake Timeout", "number", "screen", "schedule_wake_timeout", false},
    {"screen_schedule_wake_brightness", "Screen: Schedule Wake Brightness", "number", "screen", "schedule_wake_brightness", false},
    {"screen_schedule_dimmed_brightness", "Screen: Schedule Dimmed Brightness", "number", "screen", "schedule_dimmed_brightness", false},
    {"screen_schedule_clock_brightness", "Screen: Schedule Clock Brightness", "number", "screen", "schedule_clock_brightness", false},
    {"screen_schedule_clock_text_color", "Screen: Schedule Clock Text Color", "text", "screen", "schedule_clock_text_color", false},
    {"screen_daytime_brightness", "Screen: Daytime Brightness", "number", "screen", "brightness_day", false},
    {"screen_nighttime_brightness", "Screen: Nighttime Brightness", "number", "screen", "brightness_night", false},
    {"screen_brightness_dawn_time", "Screen: Brightness Dawn Time", "text", "screen", "brightness_dawn_time", false},
    {"screen_brightness_dusk_time", "Screen: Brightness Dusk Time", "text", "screen", "brightness_dusk_time", false},
    {"firmware_auto_update", "Firmware: Auto Update", "switch", "settings", "firmware_auto_update", false},
    {"firmware_update_frequency", "Firmware: Update Frequency", "select", "settings", "firmware_update_frequency", false},
    {"screen_rotation", "Screen: Rotation", "select", "settings", "screen_rotation", false},
};
inline constexpr size_t ENTITY_BACKUP_FIELD_COUNT =
    sizeof(ENTITY_BACKUP_FIELDS) / sizeof(ENTITY_BACKUP_FIELDS[0]);

// Envelope fields with no entity of their own; resolved to `target` on import.
//
// `exported` marks an alias the browser's export literal also writes, so GET has
// to emit it as well as its target to stay envelope-compatible. An alias without
// it is inbound-only: accepted on write, never emitted on read.
struct EntityBackupAlias {
  const char *section;
  const char *field;
  const char *target;
  bool exported;
};

inline constexpr EntityBackupAlias ENTITY_BACKUP_ALIASES[] = {
    {"settings", "clock_brightness", "clock_brightness_day", true},
    {"settings", "cover_art_conditions", "cover_art_attribute_conditions", false},
};
inline constexpr size_t ENTITY_BACKUP_ALIAS_COUNT =
    sizeof(ENTITY_BACKUP_ALIASES) / sizeof(ENTITY_BACKUP_ALIASES[0]);

// Slot-templated config entities. Firmware discovers the device's slot and
// subpage-chunk counts by probing these names, so no per-device constant is
// needed for the 4-chunk vs 8-chunk profiles.
struct EntitySlotTemplate {
  const char *key;
  const char *name_prefix;
  const char *name_suffix;
};

inline constexpr EntitySlotTemplate ENTITY_SLOT_TEMPLATES[] = {
    {"button_config", "Button ", " Config"},
    {"subpage_config", "Subpage ", " Config"},
    {"subpage_config_ext", "Subpage ", " Config Ext"},
    {"subpage_config_ext_2", "Subpage ", " Config Ext 2"},
    {"subpage_config_ext_3", "Subpage ", " Config Ext 3"},
    {"subpage_config_ext_4", "Subpage ", " Config Ext 4"},
    {"subpage_config_ext_5", "Subpage ", " Config Ext 5"},
    {"subpage_config_ext_6", "Subpage ", " Config Ext 6"},
    {"subpage_config_ext_7", "Subpage ", " Config Ext 7"},
};
inline constexpr size_t ENTITY_SLOT_TEMPLATE_COUNT =
    sizeof(ENTITY_SLOT_TEMPLATES) / sizeof(ENTITY_SLOT_TEMPLATES[0]);

#endif  // ESPCONTROL_ENTITY_BACKUP_MAP_GENERATED_H
