#pragma once

// Extern declarations for ESPHome-generated script pointers.
// These allow the lvgl_screenshot component to access the screensaver_wake
// script directly from C++ to wake the display before screenshot/touch.
//
// The script pointers are generated by ESPHome's codegen in main.cpp.
// They must be non-static (external linkage) to be accessible from other
// translation units. ESPHome's codegen is patched to use static=False
// for script pointers.

// Forward declare the script namespace and RestartScript template.
// The actual definition is in esphome/components/script/script.h,
// which is included by lvgl_screenshot.cpp before using these pointers.
namespace esphome {
namespace script {
template<typename... Ts> class RestartScript;
}  // namespace script
}  // namespace esphome

// Forward declarations for script pointers generated in main.cpp (global namespace)
extern esphome::script::RestartScript<> *const screensaver_wake;
extern esphome::script::RestartScript<> *const screensaver_wake_touch_guard_clear;
