"""Generate matching sensor-state case folding from pinned Unicode 16 data.

Source: https://www.unicode.org/Public/16.0.0/ucd/CaseFolding.txt
Use the locale-independent full (C + F) mappings in both runtimes.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "common/config/unicode_case_folding_16.txt"


def mappings():
    result = {}
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        fields = line.split("#", 1)[0].split(";")
        if len(fields) >= 3 and fields[1].strip() in ("C", "F"):
            result[int(fields[0], 16)] = "".join(chr(int(code, 16)) for code in fields[2].split())
    return sorted(result.items())


def outputs():
    pairs = mappings()
    comment = "// Generated by scripts/build.py from Unicode 16 CaseFolding.txt; do not edit.\n"
    ts = comment + "const folds = new Map<number, string>([\n"
    cpp = comment + "#pragma once\n#include <cstdint>\n#include <cstddef>\n\nnamespace espcontrol::sensor_colour {\n"
    cpp += "struct CaseFold { uint32_t codepoint; const char *text; };\ninline constexpr CaseFold folds[] = {\n"
    for code, folded in pairs:
        ts += f"  [0x{code:X}, {json.dumps(folded)}],\n"
        escaped = "".join(f"\\x{byte:02X}" for byte in folded.encode("utf-8"))
        cpp += f'  {{0x{code:X}, "{escaped}"}},\n'
    ts += "]);\n\nexport function sensorColourCasefold(text: string): string {\n"
    ts += '  return Array.from(text, character => folds.get(character.codePointAt(0)!) ?? character).join("");\n}\n'
    cpp += "};\n\ninline const char *casefold(uint32_t codepoint) {\n"
    cpp += "  size_t low = 0, high = sizeof(folds) / sizeof(folds[0]);\n"
    cpp += "  while (low < high) {\n    const size_t mid = low + (high - low) / 2;\n"
    cpp += "    if (folds[mid].codepoint < codepoint) low = mid + 1;\n    else high = mid;\n  }\n"
    cpp += "  return low < sizeof(folds) / sizeof(folds[0]) && folds[low].codepoint == codepoint ? folds[low].text : nullptr;\n}\n}\n"
    return {
        ROOT / "src/webserver/generated/sensor_colour_casefold.ts": ts,
        ROOT / "components/espcontrol/sensor_colour_casefold_generated.h": cpp,
    }
